### ISSUE TITLE
Add new uses of codes to codelist mapping file

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Codelists#44]
Currently missing:
- [x] Elements replicated at transaction level https://github.com/IATI/IATI-Schemas/issues/70
- [x] `planned-disbursement/@type` https://github.com/IATI/IATI-Schemas/issues/117
- [x] `iati-organisation/document-link/recipient-country` https://github.com/IATI/IATI-Schemas/issues/124
- [x] Make sure mapping of Version codelist is up to date with removed iati-activity/@version https://github.com/IATI/IATI-Schemas/issues/109

These elements were removed  in https://github.com/IATI/IATI-Schemas/issues/114 so should also be removed from the mapping file:
- [x] `location/administrative/@country`
- [x] `location/coordinates/@precision`
- [x] `location/gazetteer-entry/@gazetteer-ref`
- [x] `location/location-type/@code`

Already added/renamed:
- aidtype-flag->other-flags https://github.com/IATI/IATI-Codelists/commit/1d0231ec76b8c6c188dd5129d23fef16bd33a714

Note that the placement of `xml:lang` also changes in 2.01, but this is handled by the current mapping file, as _all_ occurrences of the `xml:lang` attribute are mapped to the Language codelist.
